server:
  port: 8081

spring:
  datasource:
    url: "jdbc:mysql://localhost:3308/book_rating_new"
    username: root
    password: Khanh2003@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: nguyenvankhanhndtt@gmail.com
    password: rcwqxkzejuvnlxtt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  signerKey: "K7j0LshncymqxUzj5inOflDE4ooSNfWFxps6VzBhVyGB2HytlsWhywvHE6VYxifs"

minio:
  url: http://localhost:9000/
  access-key: MXhWpgrVLiE077Zc14N0
  secret-key: fcdpWSCBlc3Em1PRBZYXkTSGvLi849XqrZMBy63j
  bucket-name: image-book-rate
